<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-11-16 00:30

from django.conf import settings
=======
# Generated by Django 4.2.6 on 2023-10-23 23:22

>>>>>>> origin/julian
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> origin/julian
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('mail', models.EmailField(max_length=150, verbose_name='Mail')),
                ('contraseña', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('turnos', models.CharField(max_length=50, verbose_name='Turnos')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('mail', models.EmailField(max_length=150, verbose_name='Mail')),
                ('contraseña', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('turnos', models.CharField(max_length=50, verbose_name='Turnos')),
                ('legajo', models.CharField(max_length=100, verbose_name='Legajo')),
>>>>>>> origin/julian
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('turnos', models.ManyToManyField(related_name='especialidades', to='core.turno')),
=======
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('paciente', models.ManyToManyField(to='core.paciente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
>>>>>>> origin/julian
            ],
        ),
    ]
