# Generated by Django 4.2.6 on 2023-11-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_turno_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
    ]
